version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_USER: ${DB_USER}
      MONGO_INITDB_PWD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - dbdata:/data/db
      - ./docker/initdb.d/:/docker-entrypoint-initdb.d/

volumes:
  dbdata:
